sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t farhan/docker-react  .

script:
  - docker run -e CI=true farhan/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-west-1-156578752480'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
